-- 压测和生产可观测性需要毫秒级时间，避免短操作全部被截断到整秒。
-- MySQL 8.0 在线修改；执行前仍建议在生产环境确认表大小和 DDL 窗口。
ALTER TABLE analysis_task
    MODIFY COLUMN created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN started_at DATETIME(3) NULL COMMENT '开始处理时间',
    MODIFY COLUMN completed_at DATETIME(3) NULL COMMENT '完成时间',
    MODIFY COLUMN updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE task_outbox
    MODIFY COLUMN available_at DATETIME(3) NOT NULL COMMENT '最早可投递时间',
    MODIFY COLUMN sent_at DATETIME(3) NULL COMMENT '成功投递时间',
    MODIFY COLUMN created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';
